### ISSUE TITLE
https://www.freecodecamp.com/challenges/profile-lookup

### ISSUE THREAD

**Issue by PanTrojuhelnik** [PanTrojuhelnik/Hello-World#1]
function lookUpProfile(firstName, prop){
  var i = 0;
  while (i < contacts.length) {
if (firstName == contacts[i].firstName) {
  
  if (contacts[i].hasOwnProperty(prop)) {
    return prop;
  }
}
    if (i == (contacts.length - 1)) {
      return "No such contact";
    }
      i++;
  }

**Comment by straiki** [comment]
par veci
`  var i = 0;
  while (i < contacts.length) {
    if (firstName === contacts[i].firstName) {
      return firstName;
    } i++;
    if (firstName === contacts.length -1) {
      return "No such contact";
    }
`

- proc while?
- proc vracis firstName?
- proc `(firstName == contacts.length -1)` ? pokud se jmeno rovna objektu na posledni pozici?

**Comment by pajuscz** [comment]
Jn souhlasim s Vahyho commentem.

- Proc pouzivas ten `while`? Neni to spatne, ale je to hure citelne a asi i pochopitelne
- Proc vracis `prop` to je nazev te property ty musis vratit tu property pro dany objekt
- Jeste ti tam chybi jeden 'ifik' co se stane kdyz ta property neexistuje, mel bys vratit `No such property`

**Comment by PanTrojuhelnik** [comment]
kura tak ted jsem si to cele dojebal :D tak asi zitra a dneska uz to jebu

**Comment by PanTrojuhelnik** [comment]
var i;
for (i=0;i < contacts[i].length; i++) {
  if (firstName === contacts[i].firstName) {
  }
  else return "No such contact";
}
       
  for (i=0;i < contacts[i].likes; i++)
    if (contacts[i].likes === prop) { 
    } else return "No such property";
           
      return firstName + prop;

**Comment by PanTrojuhelnik** [comment]
už nad tímhle sedím další hodinu, snažím se pochopit jednotlivé prvky, co se chce a jak to vlastně uchopit, co mi ukázal 4K v práci oproti tomu, co se z toho stalo, na druhém monitoru major v Dotě 2 a jako focus tak na 50%, ale stejně vždy dojdu k tomu, že to nechápu :D , že nevím jak vlastně odkázat tu for loopu na ten prvek a že nevím co s tím chcu dělat a co vlastně chcu, aby z toho zůstalo :-/

**Comment by pajuscz** [comment]
Kemko jedna vec... 
```
var i;
for( i = 0; i < contacts[i].length; i++)
{
 ...
}
for (i;i < neco[i]; neco.lenght; i++)
{
...
}
```

Kdyz udelas to `var i;` na zacatku. Tak to znamena ze ta promenna `i` existuje po celem behu kodu a ty ji muzes taky vsude menit a pristupovat k ni.
Zakladni practice je 
1. Vytvaret promenne az jak je potrebujes (co nejblize ke kusu kodu, kde je treba ji vyuzit)
2. Pouzivat je jen v kusu kodu, kde je potrebujes (jinak muze dojit k tomu, ze pracujes s promennou, ve ktere jsou hodnoty, ktere uplne neocekavas) _Treba v tom kusu kodu nahore vytvoris i na zacatku pak v prvnim cyklu neco provadis a v druhem cyklu pouzivas tu samou, uz editovanou promennou `i`. Muze to byt umysl, ale pokud je, tak to znamena spatny navrh._

Takze u tech FOR cyklu je lepsi psat
```
for(var i = 0; i < array.length; i++)
{
 necoProved(array[i])
}
```
Ta promenna `i` je platna je pro ten for cyklus. V tech kudrnatych zavorkach od `{` po `}`. Pak uz k ni nemas pristup a zbytecne to nebude plest... v dalsim cyklu muzes vytvorit novou promennou zase udelas `for(var i ...` a mas jistotu, ze se znova vytovri a nebude tam nejaky balast.

**Comment by pajuscz** [comment]
Jinak Obecne.. vzdycky se na to divej jako _Rozdel a panuj_. Konkretne u tohoto ukolu

1. Projdi vsechny kontakty a najdi ten, hledany. _Ten u ktereho je `firstName == contacts[i].firstName`_
2. Jakmilenajdes ten se shodujicim se `fristName`, tak zkontroluj jestli ma i pozadovanou property `prop`
3. Kdyz ji ma, tak ji vrat `return contacts[i][prop]`
4. Kdyz ji nema vrat `return "No such property"`
5. Postarej se nejak o to, ze kdyz neexistuje dany contact s odpovidajicim `firstName`, tak vrat `"No such contact"` - necham na tobe jako cviceni :P kam to placnout nebo jak to udelat.

Neznam vsechny vyfikundace javascriptu a nabusil jsem to jen tak na rychlo, ale je to jeden FOR cyklus a dva zanorene IFiky.

**Comment by PanTrojuhelnik** [comment]
já bych to chtěl zapsat nějak jednoduše, ale nic jako pokud to, tak toto neni :-/ musím focusnout, to není tak těžké, už mi to ukazoval i říkal i 4k, ale já to prostě nedokážu všechno utříbit

**Comment by pajuscz** [comment]
Co to podle tebe znamena jednoduse? 
Pokut to, tak toto neni 👨‍💻  je uplne normalni vec na tehle urovni.

**Comment by PanTrojuhelnik** [comment]
ale to nezapisu v jednom radku 🗡

**Comment by pajuscz** [comment]
O tom to neni... Je dulezite, at to dela efektivne to co ma a at to pochopi i jiny clovek.

**Comment by PanTrojuhelnik** [comment]
for (var i=0; i < contacts.length; i++) {
  if (firstName === contacts[i].firstName) { **Tady spravne vybiras contact se shodnym firstName**
  return contacts[i].firstName; **Ale tady vracis firstName z nalezeneho contactu. Proc? oni chteji abys vratil to co urcuje funkce tou promennou prop**
  }
    else return "No such contact"; ** zkus si v hlave rict, co se stane. Jak projizdi ten For cyklus. Vezme prvni z tech kontaktu, zjisti ze firstName se neshoduje, tak hend skoci do te vetve else a vrati No such contact - To je spatne**
  //toto projede firstName objektu a pokud narazi na shodu, tak vypise, pokud ne, vypise string z else return
}
  for (var o=0; o < contacts.length; o++) { ** nepouzivej o jako nazev promenne, ani l - lehce se to ztrati a vypada to jako nula resp. jednicka **
  if (prop === contacts[o].likes) { ** me prijde, ze si nepochopil zadani nemas hledat likes toho objektu **
  return contacts[o].likes;
  }
    else return "No such property";
  //toto projede likes objektu a pokud narazi na shodu, tak vypise, pokud ne, vypise string z else return
}

**Comment by PanTrojuhelnik** [comment]
me z toho za chvilu jebne... :-!

**Comment by PanTrojuhelnik** [comment]
for (var indOne=0; indOne < contacts.length; indOne++) {
  if (firstName === contacts[indOne].firstName) {
    return contacts[indOne].likes;
 }
/*for (var indTwo=0; indTwo < contacts.length; indTwo++) {
  if (prop === contacts[indTwo].likes) {
    return contacts[indTwo].
  }
  */
  if (firstName !== contacts[indOne].firstName) {
  return "No such contact";
  }
  else if (prop !== contacts[indTwo].likes) {
  return "No such property";
  }
}

**Comment by PanTrojuhelnik** [comment]
zacinam byt fakt vytoceny, uz jsem mel kazdy mozny vysledek z tech testu, skoro z tech peti aspon jednou jeden nebo 2, ale proste nechapu jak to jako za sebe naskladat ty ify, aby to davalo smysl, asi to tu rozmlatim

**Comment by PanTrojuhelnik** [comment]
```
for (var indOne=0; indOne < contacts.length; indOne++) {
  if (prop !== contacts[indOne].likes) {
     return "No such property";
  }
  else if (firstName !== contacts[indOne].firstName) {
     return "No such contact";
  }
  else if (firstName === contacts[indOne].firstName) {
    return contacts[indOne].likes + [prop];
  }
}
```


posledni verze, co mam

**Comment by straiki** [comment]
k posledni verzi..  kdyz bych to vzal slovne.. projdi vsechny prvky pole contacts a pokud nazev toho co mam vypsat neni to co ma dany kontakt rad, tak rekni "no such property" a skonci.. pokud ne, tak jestli jmeno se nerovna jmenu kontaktu pak skonci a rekni "no such contact"a kdyz ne, tak jestli se jmeno rovna jmenu kontaktu tak vypis co ma ten kontakt rad a k tomu pripoj pole ve kterem je jeden prvek s nazvem toho co mam vypsat..

Logicka flow je jendoducha.. projdi pres vsechny prvky v poli kontakty a pokud jmeno je stejne jako jmeno kontaktu (tvuj treti if) pak udelej nasledujici: vypis hodnotu property kterou hledam nebo rekni ze dana properta neexistuje.

pokud jsem zadny kontakt s danym jmenem nenasel, pak napis "No such contact"

**Comment by pajuscz** [comment]
Editoval jsem tvuj prispevek - pridal komenty mrkni
-- to uz je ale k tomu postu co si psal predtim https://github.com/PanTrojuhelnik/Hello-World/issues/1#issuecomment-298164138

Jinak to co rika vahy no... jednoduchy flow.
Nechapu moc proc tam porad cpes tu property `.likes` - vysvetlit


>>> ja nevim jak to zapsat, nevim jestli pouzit tu promennou a dat ji do zavorek a nebo zapsat s teckami nevim co delat to odkazat se na tu promennou a nebo na tu propertu v tom objektu contacts, to je to co nechapu celou dobu, kdyz uz me neco napadne, tak nevim jak to zapsat

**Comment by pajuscz** [comment]
BTW. chapes co znamena ta promenna `prop`?
V te je ulozeno jakou property mas vybrat z toho daneho kontaktu. Jestli treba `likes` nebo `firstName` atd.

**Comment by roxx1k** [comment]
Caues,  rekl jsem, ze sem pridam taky nejaky comment, tak tady me mate. :)

Zaprve, urcite bych se drzel standartniho a osvedceneho oznackovani pomocnych promennych v cyklech. takove "i, j, k ..." jednoduche, snadno zapsatelne, snadno citelne. Proste nevidim duvod to oznacovat jinak.

Zadruhe, urcite chces prvni hledat shodu se jmenem `firstName` a az potom zjistovat jestli "ma vlastni property" a nebo ne. Strucne receno, jak uz tady zminoval Paja:
1) najdes shodu jmen. vstupni parametr firstName bude rovno hodnote property "firstName" daneho pole `firstName == contacts[i].firstName`
2) zjistis jestli existuje property zadana jako vstupni parametr. Pokud existuje, pak vratis hodnotu te property `return contacts[i][prop]`.
Pokud neexistuje vratis "No such property"
3)  pokud pri poslednim pruchodu cyklu nenajdes shodu jmena, pak vratis "No such name"

**Comment by roxx1k** [comment]
Nejbliz k uspechu ma zatim tahle ta tvoje verze:
``` function lookUpProfile(firstName, prop){
var i = 0;
while (i < contacts.length) {
if (firstName == contacts[i].firstName) {

if (contacts[i].hasOwnProperty(prop)) {
return prop;
}
}
if (i == (contacts.length - 1)) {
return "No such contact";
}
i++;
} 
```

doplnis jen par veci a mas hotovo.

1. misto `return prop` vratis hodnotu te `prop`, jelikoz je definovana jako "klic : hodnota", takze vratis tu hodnotu
2. dopln jeste to vraceni "No such property"za `if (contacts[i].hasOwnProperty(prop)) {
return prop;
}` kdyz teda zjistis, ze dana hledana properta neexistuje

a mas vlastne hotovo

**Comment by PanTrojuhelnik** [comment]
jestli nekdy budu chapat, ze vlastne to vyvolava toto a toto porovnava toto, tak budu stastny, pro ted vidim jenom, ze:
var i = 0;
while (i < contacts.length) {
if (firstName == contacts[i].firstName) {

if (contacts[i].hasOwnProperty(prop)) {
return contacts[i][prop];
}
}
if (i == (contacts.length - 1)) {
return "No such contact";
}
  i++;

...s timhle mam pri testu 5/6
![image](https://cloud.githubusercontent.com/assets/26097252/25563456/e3b69176-2d9c-11e7-99ce-594b4ff33815.png)

**Comment by PanTrojuhelnik** [comment]
... a kdyz to chci osetrit, tak: svete div se:
![image](https://cloud.githubusercontent.com/assets/26097252/25563502/8b3c5520-2d9d-11e7-91ea-1cd26b336682.png)

osetrit, chapej jako:
var i = 0;
while (i < contacts.length) {
if (firstName == contacts[i].firstName) {

if (contacts[i].hasOwnProperty(prop)) {
return contacts[i][prop];
}
}
if (i == (contacts.length - 1)) {
return "No such contact";
}
if (i !== (contacts.length -1)) {
return "No such property";
}
  i++;
}

**Comment by PanTrojuhelnik** [comment]
![image](https://cloud.githubusercontent.com/assets/26097252/25563619/d1ec645e-2d9f-11e7-9ec0-00490cd9020e.png)

ehm...

no ale ted zpet k Pajovi a Tomovi:
jak bych to vlastne zapsal bez toho while a ... nejdulezitejsi otazka, co vlastne jsem ted v hlave totalne nedal: jak je mozne, ze najednou v tom celku funguje 'else' <neco> ????????????????

final version so far:

var i = 0;
while (i < contacts.length) {
if (firstName === contacts[i].firstName) {

if (contacts[i].hasOwnProperty(prop)) {
return contacts[i][prop];
}
  else return "No such property";
}
if (i === (contacts.length - 1)) {
return "No such contact";
}
  i++;
}

**Comment by straiki** [comment]
![image](https://cloud.githubusercontent.com/assets/724967/25566074/3f609e1e-2dd3-11e7-9a0a-1581b54fe9aa.png)
Takhle se to da prepsat na for.. jak budu mit chvili ukazu co a jak jeste..

**Comment by straiki** [comment]
![image](https://cloud.githubusercontent.com/assets/724967/25566189/be43b1e8-2dd4-11e7-86d0-560d36275e11.png)
Dalsi moznost jak se zbavit jednoho ifu :) (jeste byt tam u toho kde se nastavuje "ret" mohl byt break; ale v tomhle pripade neni nutny.

>tu se snazim vstrebat uziti toho "ret"  - nemuzu se zorientovat

**Comment by straiki** [comment]
![image](https://cloud.githubusercontent.com/assets/724967/25566269/f031737e-2dd5-11e7-89e2-399e7b05a795.png)

tahle varianta uz se mi i celkem libi :)

**Comment by roxx1k** [comment]
Tenhle zapis, ze pro return pouzivas || vidim poprve :) jen pro jistotu jestli to chapu dobre, ten `ret = contacts[i][prop] || "No such property";` ti vrati pozadovanou hodnotu property ´prop´ protoze je jako prvni a pokud se stane, ze existovat nebude a tim padem nebude mit zadnou hodnotu, tak se pristoupi k druhe casti a vrati se hlaska.

Dobi k te tvoji otazce o ELSE, to zalezi jak a kde ten else pouzijes. Kdyz chces například prohledavat vsechny prvky pole podle jmena, tak prece nemuzes napsat else ve kterem vracis hlasku "No such contact" za if, ve kterem porovnavas jestli dany prvek pole ma stejne jmeno. Tim vzdycky bud najdes shodu jmena na prvni pozici pole a nebo ti vrati tu hlasku. Jinak receno, nebudes nikdy porovnavat nic jineho nez prvni prvek pole.

**Comment by straiki** [comment]
> Tenhle zapis, ze pro return pouzivas || vidim poprve :) jen pro jistotu jestli to chapu dobre, ten ret = contacts[i][prop] || "No such property"; ti vrati pozadovanou hodnotu property ´prop´ protoze je jako prvni a pokud se stane, ze existovat nebude a tim padem nebude mit zadnou hodnotu, tak se pristoupi k druhe casti a vrati se hlaska.

jj, v podstate je to zkraceny zapis.. `ret = contacts[i][prop] ? contacts[i][prop] : "No such property"` prvni cast se vyhodnoti a pokud to neni false (null, false, 0, undefined) tak se to pouzije, jinak se pouzije ta druha strana :) tehle zapis se pouziva pro nastaveni defaulti hodnoty :)

**Comment by pajuscz** [comment]
Po vzoru vahyho - nejlepsi kod mi pripada tento.
@straiki Jedine co bych tam zmenil je, ze vracis tu property hned jak ji najdes - at zbytecne nemusis cyklit dal. Asi bych si to neukladal do `ret` a vracel az po pruchodu toho cyklu > nejak to ve mne vzbuzuje: kdyz to najdu, tak v dalsim pruchodu cyklu se hodnota `ret` muze jeste zmenit, to je bud hack nebo moznost chyby.

```
function lookUpProfile(firstName, prop){
  for(var i = 0; i < contacts.length; i++)
  {
    if(contacts[i].firstName === firstName)
    {
       return contacts[i][prop] || "No such property"; // tohle je dobra vychytavka
    }
  }
  return "No such contact";
}
```

a jinak takove to `if (contact.length - 1 === i)` ke kontrole toho ze prochazim posledni prvek, je uplne zbytecny kus kodu imho. Pokud ten cyklus projede pres vsechny prvky a v zadnem nenajde first name - je jasne ze tam takovy prvek neni.

**Comment by straiki** [comment]
No jasne, to je s tim breakem (co jsem psal predtim) a taky diky domu ze jsem to napsal kazde za minutu s Kristynou na kline a potreboval jsem pryc od pc 🗡 :D

**Comment by pajuscz** [comment]
Ajo vidis, ja jsem tu vetu s brekem vcera cet a dneska jak sem se ktomu vracel tak prehlid. Novy level 💃 Extremniho programovani :D "kiddo on klino" 🗡 :D pica ta `dagger` me sere nemuzu normane psat smajliky.
